# Generated by Django 2.2.14 on 2020-09-21 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200921_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vergi_numarası',
            field=models.BigIntegerField(default=1000000000, validators=[django.core.validators.MinValueValidator(
                1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
