# Generated by Django 2.2.14 on 2020-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200917_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
