# Generated by Django 2.2.14 on 2020-09-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
