# Generated by Django 2.2.14 on 2020-09-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ürün'),
    ]

    operations = [
        migrations.AddField(
            model_name='ürün',
            name='fiyat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ürün',
            name='fotoğraf',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ürün',
            name='indirimli_fiyat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ürün',
            name='isim',
            field=models.CharField(default='', max_length=100),
        ),
    ]
