# Generated by Django 2.2.14 on 2020-09-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200921_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Öne_Çıkanlar_Ürün',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(default='', max_length=100)),
                ('fotoğraf', models.ImageField(null=True, upload_to='')),
                ('açıklama', models.CharField(max_length=1000)),
            ],
        ),
    ]
